CREATE TABLE STOCK_CODE
(
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	CODE VARCHAR(200) NULL,
	DESCRIPTION VARCHAR(200) NULL,
	CREATED_AT VARCHAR(200) NULL,
	UPDATED_AT VARCHAR(200) NULL,
)
COMMENT 'STOCK CODE LOOKUP' ENGINE=INNODB;

CREATE TABLE STOCK
(
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	STOCK_CODE_ID INT(11) NOT NULL,
	QUANTITY INT(11) DEFAULT 0 NOT NULL,
	CREATED_AT VARCHAR(200) NULL,
	UPDATED_AT VARCHAR(200) NULL,
)
COMMENT 'STOCK' ENGINE=INNODB;
ALTER TABLE STOCK ADD CONSTRAINT FK_STOCK_STOCK_CODE_ID FOREIGN KEY (STOCK_CODE_ID) REFERENCES STOCK_CODE(ID);

CREATE TABLE DENTAL_ORDER
(
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	CLIENT_ID INT(11) NOT NULL,
	ORDER_NO VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TOTAL_AMOUNT INT(11) DEFAULT 0 NOT NULL,
	DATE_DELIVERY DATETIME NULL,
	STATUS INT(11) DEFAULT 0 NOT NULL,
	CREATED_AT VARCHAR(200) NULL,
	UPDATED_AT VARCHAR(200) NULL,
)
COMMENT 'DENTAL ORDER' ENGINE=INNODB;
CREATE INDEX IX_DENTAL_ORDER_CLIENT_ID ON DENTAL_ORDER (ORDER_NO);
ALTER TABLE DENTAL_ORDER ADD CONSTRAINT FK_DENTAL_ORDER_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID);

CREATE TABLE ORDER_ITEM
(
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	ORDER_ID INT(11) NOT NULL,
	STOCK_CODE_ID INT(11) NOT NULL,
	QUANTITY INT(11) DEFAULT 0 NOT NULL,
	CREATED_AT VARCHAR(200) NULL,
	UPDATED_AT VARCHAR(200) NULL,
)
COMMENT 'DENTAL ORDER' ENGINE=INNODB;
ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ORDER_ITEM_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES DENTAL_ORDER(ID);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ORDER_ITEM_STOCK_CODE_ID FOREIGN KEY (STOCK_CODE_ID) REFERENCES STOCK_CODE(ID);
